server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

    session:
      tracking-modes: cookie

spring:
  application:
    name: spring-cafe

  mvc:
    hidden-method:
      filter:
        enabled: true

  mustache:
    suffix: .html
    servlet:
      cache: false
      expose-session-attributes: true
      expose-request-attributes: true

  profiles:
    default: dev

  datasource:
    url: 'jdbc:mysql:// localhost:3306/spring_cafe?useSSL=false & allowPublicKeyRetrieval=true'
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
    username: 'soap'
    password: 'Soap0000'
    hikari:
      connection-timeout: 1000
      connection-test-query: SELECT 1

---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: 'jdbc:h2:tcp://localhost/~/springcafe_test'
    username: 'sa'
    password: ''

  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql

---
spring:
  config:
    activate:
      on-profile: dev
---


